package entities;
// Generated Dec 31, 2019, 9:04:57 AM by Hibernate Tools 5.1.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Chuyenbay generated by hbm2java
 */
@Entity
@Table(name = "chuyenbay")
public class Chuyenbay implements java.io.Serializable {

	private Integer macb;
	private String tencb;
	private Date ngaydi;
	private int sogheloai1;
	private long giagheloai1;
	private int sogheloai2;
	private long giagheloai2;
	private Set<Ve> ves = new HashSet<Ve>(0);

	public Chuyenbay() {
	}

	public Chuyenbay(int macb) {
		this.macb = macb;
	}

	public Chuyenbay(String tencb, Date ngaydi, int sogheloai1, long giagheloai1, int sogheloai2, long giagheloai2) {
		this.tencb = tencb;
		this.ngaydi = ngaydi;
		this.sogheloai1 = sogheloai1;
		this.giagheloai1 = giagheloai1;
		this.sogheloai2 = sogheloai2;
		this.giagheloai2 = giagheloai2;
	}

	public Chuyenbay(String tencb, Date ngaydi, int sogheloai1, long giagheloai1, int sogheloai2, long giagheloai2,
			Set<Ve> ves) {
		this.tencb = tencb;
		this.ngaydi = ngaydi;
		this.sogheloai1 = sogheloai1;
		this.giagheloai1 = giagheloai1;
		this.sogheloai2 = sogheloai2;
		this.giagheloai2 = giagheloai2;
		this.ves = ves;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "macb", unique = true, nullable = false)
	public Integer getMacb() {
		return this.macb;
	}

	public void setMacb(Integer macb) {
		this.macb = macb;
	}

	@Column(name = "tencb", nullable = false, length = 250)
	public String getTencb() {
		return this.tencb;
	}

	public void setTencb(String tencb) {
		this.tencb = tencb;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaydi", nullable = false, length = 10)
	public Date getNgaydi() {
		return this.ngaydi;
	}

	public void setNgaydi(Date ngaydi) {
		this.ngaydi = ngaydi;
	}

	@Column(name = "sogheloai1", nullable = false)
	public int getSogheloai1() {
		return this.sogheloai1;
	}

	public void setSogheloai1(int sogheloai1) {
		this.sogheloai1 = sogheloai1;
	}

	@Column(name = "giagheloai1", nullable = false, precision = 10, scale = 0)
	public long getGiagheloai1() {
		return this.giagheloai1;
	}

	public void setGiagheloai1(long giagheloai1) {
		this.giagheloai1 = giagheloai1;
	}

	@Column(name = "sogheloai2", nullable = false)
	public int getSogheloai2() {
		return this.sogheloai2;
	}

	public void setSogheloai2(int sogheloai2) {
		this.sogheloai2 = sogheloai2;
	}

	@Column(name = "giagheloai2", nullable = false, precision = 10, scale = 0)
	public long getGiagheloai2() {
		return this.giagheloai2;
	}

	public void setGiagheloai2(long giagheloai2) {
		this.giagheloai2 = giagheloai2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chuyenbay")
	public Set<Ve> getVes() {
		return this.ves;
	}

	public void setVes(Set<Ve> ves) {
		this.ves = ves;
	}

}
