package entities;
// Generated Dec 31, 2019, 9:04:57 AM by Hibernate Tools 5.1.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ve generated by hbm2java
 */
@Entity
@Table(name = "ve")
public class Ve implements java.io.Serializable {

	private Integer mave;
	private Chuyenbay chuyenbay;
	private String hotenhanhkhach;
	private String cmnd;
	private int loaighe;
	private int giaghe;

	public Ve() {
	}

	public Ve(Chuyenbay chuyenbay, String hotenhanhkhach, String cmnd, int loaighe, int giaghe) {
		this.chuyenbay = chuyenbay;
		this.hotenhanhkhach = hotenhanhkhach;
		this.cmnd = cmnd;
		this.loaighe = loaighe;
		this.giaghe = giaghe;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "mave", unique = true, nullable = false)
	public Integer getMave() {
		return this.mave;
	}

	public void setMave(Integer mave) {
		this.mave = mave;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "macb", nullable = false)
	public Chuyenbay getChuyenbay() {
		return this.chuyenbay;
	}

	public void setChuyenbay(Chuyenbay chuyenbay) {
		this.chuyenbay = chuyenbay;
	}

	@Column(name = "hotenhanhkhach", nullable = false, length = 250)
	public String getHotenhanhkhach() {
		return this.hotenhanhkhach;
	}

	public void setHotenhanhkhach(String hotenhanhkhach) {
		this.hotenhanhkhach = hotenhanhkhach;
	}

	@Column(name = "cmnd", nullable = false, length = 20)
	public String getCmnd() {
		return this.cmnd;
	}

	public void setCmnd(String cmnd) {
		this.cmnd = cmnd;
	}

	@Column(name = "loaighe", nullable = false)
	public int getLoaighe() {
		return this.loaighe;
	}

	public void setLoaighe(int loaighe) {
		this.loaighe = loaighe;
	}

	@Column(name = "giaghe", nullable = false)
	public int getGiaghe() {
		return this.giaghe;
	}

	public void setGiaghe(int giaghe) {
		this.giaghe = giaghe;
	}

}
