package entities;
// Generated Nov 26, 2019, 10:03:09 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InvoiceDetailId generated by hbm2java
 */
@Embeddable
public class InvoiceDetailId implements java.io.Serializable {

	private int invoiceId;
	private int productId;

	public InvoiceDetailId() {
	}

	public InvoiceDetailId(int invoiceId, int productId) {
		this.invoiceId = invoiceId;
		this.productId = productId;
	}

	@Column(name = "invoice_id", nullable = false)
	public int getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(int invoiceId) {
		this.invoiceId = invoiceId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InvoiceDetailId))
			return false;
		InvoiceDetailId castOther = (InvoiceDetailId) other;

		return (this.getInvoiceId() == castOther.getInvoiceId()) && (this.getProductId() == castOther.getProductId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getInvoiceId();
		result = 37 * result + this.getProductId();
		return result;
	}

}
