package entities;
// Generated Dec 9, 2019, 1:50:24 AM by Hibernate Tools 5.1.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Chitietchuyenbay generated by hbm2java
 */
@Entity
@Table(name = "chitietchuyenbay")
public class Chitietchuyenbay implements java.io.Serializable {

	private Integer mact;
	private Chuyenbay chuyenbay;
	private Sanbay sanbay;
	private int thoigiandung;
	private String mota;

	public Chitietchuyenbay() {
	}

	public Chitietchuyenbay(Chuyenbay chuyenbay, Sanbay sanbay, int thoigiandung, String mota) {
		this.chuyenbay = chuyenbay;
		this.sanbay = sanbay;
		this.thoigiandung = thoigiandung;
		this.mota = mota;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "mact", unique = true, nullable = false)
	public Integer getMact() {
		return this.mact;
	}

	public void setMact(Integer mact) {
		this.mact = mact;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "macb", nullable = false)
	public Chuyenbay getChuyenbay() {
		return this.chuyenbay;
	}

	public void setChuyenbay(Chuyenbay chuyenbay) {
		this.chuyenbay = chuyenbay;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "masb", nullable = false)
	public Sanbay getSanbay() {
		return this.sanbay;
	}

	public void setSanbay(Sanbay sanbay) {
		this.sanbay = sanbay;
	}

	@Column(name = "thoigiandung", nullable = false)
	public int getThoigiandung() {
		return this.thoigiandung;
	}

	public void setThoigiandung(int thoigiandung) {
		this.thoigiandung = thoigiandung;
	}

	@Column(name = "mota", nullable = false, length = 500)
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

}
