package entities;
// Generated Dec 9, 2019, 1:50:24 AM by Hibernate Tools 5.1.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hanhkhach generated by hbm2java
 */
@Entity
@Table(name = "hanhkhach")
public class Hanhkhach implements java.io.Serializable {

	private Integer mahk;
	private String hoten;
	private String cmnd;
	private Date ngaysinh;
	private Set<Ve> ves = new HashSet<Ve>(0);

	public Hanhkhach() {
	}

	public Hanhkhach(Integer mahk) {
		super();
		this.mahk = mahk;
	}

	public Hanhkhach(String hoten, String cmnd, Date ngaysinh) {
		this.hoten = hoten;
		this.cmnd = cmnd;
		this.ngaysinh = ngaysinh;
	}

	public Hanhkhach(String hoten, String cmnd, Date ngaysinh, Set<Ve> ves) {
		this.hoten = hoten;
		this.cmnd = cmnd;
		this.ngaysinh = ngaysinh;
		this.ves = ves;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "mahk", unique = true, nullable = false)
	public Integer getMahk() {
		return this.mahk;
	}

	public void setMahk(Integer mahk) {
		this.mahk = mahk;
	}

	@Column(name = "hoten", nullable = false, length = 100)
	public String getHoten() {
		return this.hoten;
	}

	public void setHoten(String hoten) {
		this.hoten = hoten;
	}

	@Column(name = "cmnd", nullable = false, length = 20)
	public String getCmnd() {
		return this.cmnd;
	}

	public void setCmnd(String cmnd) {
		this.cmnd = cmnd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaysinh", nullable = false, length = 10)
	public Date getNgaysinh() {
		return this.ngaysinh;
	}

	public void setNgaysinh(Date ngaysinh) {
		this.ngaysinh = ngaysinh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hanhkhach")
	public Set<Ve> getVes() {
		return this.ves;
	}

	public void setVes(Set<Ve> ves) {
		this.ves = ves;
	}

}
