package entities;
// Generated Dec 9, 2019, 1:50:24 AM by Hibernate Tools 5.1.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sanbay generated by hbm2java
 */
@Entity
@Table(name = "sanbay")
public class Sanbay implements java.io.Serializable {

	private Integer masanbay;
	private String tensanbay;
	private Set<Chuyenbay> chuyenbaysForMasbden = new HashSet<Chuyenbay>(0);
	private Set<Chitietchuyenbay> chitietchuyenbays = new HashSet<Chitietchuyenbay>(0);
	private Set<Chuyenbay> chuyenbaysForMasbdi = new HashSet<Chuyenbay>(0);

	public Sanbay(Integer masanbay) {
		super();
		this.masanbay = masanbay;
	}

	public Sanbay() {
	}

	public Sanbay(String tensanbay) {
		this.tensanbay = tensanbay;
	}

	public Sanbay(String tensanbay, Set<Chuyenbay> chuyenbaysForMasbden, Set<Chitietchuyenbay> chitietchuyenbays,
			Set<Chuyenbay> chuyenbaysForMasbdi) {
		this.tensanbay = tensanbay;
		this.chuyenbaysForMasbden = chuyenbaysForMasbden;
		this.chitietchuyenbays = chitietchuyenbays;
		this.chuyenbaysForMasbdi = chuyenbaysForMasbdi;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "masanbay", unique = true, nullable = false)
	public Integer getMasanbay() {
		return this.masanbay;
	}

	public void setMasanbay(Integer masanbay) {
		this.masanbay = masanbay;
	}

	@Column(name = "tensanbay", nullable = false, length = 250)
	public String getTensanbay() {
		return this.tensanbay;
	}

	public void setTensanbay(String tensanbay) {
		this.tensanbay = tensanbay;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sanbayByMasbden")
	public Set<Chuyenbay> getChuyenbaysForMasbden() {
		return this.chuyenbaysForMasbden;
	}

	public void setChuyenbaysForMasbden(Set<Chuyenbay> chuyenbaysForMasbden) {
		this.chuyenbaysForMasbden = chuyenbaysForMasbden;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sanbay")
	public Set<Chitietchuyenbay> getChitietchuyenbays() {
		return this.chitietchuyenbays;
	}

	public void setChitietchuyenbays(Set<Chitietchuyenbay> chitietchuyenbays) {
		this.chitietchuyenbays = chitietchuyenbays;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sanbayByMasbdi")
	public Set<Chuyenbay> getChuyenbaysForMasbdi() {
		return this.chuyenbaysForMasbdi;
	}

	public void setChuyenbaysForMasbdi(Set<Chuyenbay> chuyenbaysForMasbdi) {
		this.chuyenbaysForMasbdi = chuyenbaysForMasbdi;
	}

}
