package entities;
// Generated Dec 9, 2019, 1:50:24 AM by Hibernate Tools 5.1.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ve generated by hbm2java
 */
@Entity
@Table(name = "ve")
public class Ve implements java.io.Serializable {

	private Integer mave;
	private Chuyenbay chuyenbay;
	private Hanhkhach hanhkhach;
	private int soghe;
	private int loaighe;
	private double giaghe;

	public Ve() {
	}

	public Ve(Chuyenbay chuyenbay, Hanhkhach hanhkhach, int soghe, int loaighe, double giaghe) {
		this.chuyenbay = chuyenbay;
		this.hanhkhach = hanhkhach;
		this.soghe = soghe;
		this.loaighe = loaighe;
		this.giaghe = giaghe;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "mave", unique = true, nullable = false)
	public Integer getMave() {
		return this.mave;
	}

	public void setMave(Integer mave) {
		this.mave = mave;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "macb", nullable = false)
	public Chuyenbay getChuyenbay() {
		return this.chuyenbay;
	}

	public void setChuyenbay(Chuyenbay chuyenbay) {
		this.chuyenbay = chuyenbay;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mahk", nullable = false)
	public Hanhkhach getHanhkhach() {
		return this.hanhkhach;
	}

	public void setHanhkhach(Hanhkhach hanhkhach) {
		this.hanhkhach = hanhkhach;
	}

	@Column(name = "soghe", nullable = false)
	public int getSoghe() {
		return this.soghe;
	}

	public void setSoghe(int soghe) {
		this.soghe = soghe;
	}

	@Column(name = "loaighe", nullable = false)
	public int getLoaighe() {
		return this.loaighe;
	}

	public void setLoaighe(int loaighe) {
		this.loaighe = loaighe;
	}

	@Column(name = "giaghe", nullable = false, precision = 22, scale = 0)
	public double getGiaghe() {
		return this.giaghe;
	}

	public void setGiaghe(double giaghe) {
		this.giaghe = giaghe;
	}

}
